apiVersion: v1
kind: ConfigMap
metadata:
  name: camel-solace-pubsub-test
data:
  application-send.properties: |-
    connection.type=SOLACE
    connection.remoteUrl=tcp://ha-pubsubplus:55555
    connection.username=test
    connection.password=secret
    send.enabled=true
    send.threads=2
    send.count=50000
    send.queue=q1
    send.delay=0
    send.shutdownEnabled=true
    send.message=Hello World!
    send.headers={myproperty: "myvalue", foo: "bar"}
  application-receive.properties: |-
    connection.type=AMQP
    connection.remoteUrl=amqp://ha-pubsubplus:5672
    connection.username=test
    connection.password=secret
    receive.enabled=true
    receive.queue=q1
    receive.transacted=false
    receive.concurrentConsumers=2
    receive.shutdownIdleSec=15
