kind: ConfigMap
apiVersion: v1
metadata:
  name: ha-env
data:
  # These are only picked up the first time when the broker is created
  username_test_password: secret
  username_test_globalaccesslevel: read-write
  
